dataset:
  name: gb_oral_evidence
  prefix: gb-parl
  title: UK Parliament Oral Evidence
  summary: Oral evidence is usually taken in public. Oral evidence sessions are usually broadcast live on television and archived on www.parliamentlive.tv.
  tags:
    - lobbying
    - legislative
  index_url: https://committees.parliament.uk/publications/oral-evidence/
  licence:
    name: Open Parliament Licence v3.0
    url: https://www.parliament.uk/site-information/copyright-parliament/open-parliament-licence/
coverage:
  countries:
    - gb
  frequency: monthly
publisher:
  name: UK Parliament
  description: The UK Parliament is the supreme legislative body in the United Kingdom, consisting of the House of Commons, the House of Lords, and the Sovereign. It is responsible for making and passing laws, and its activities include holding oral evidence sessions that are often broadcast live and archived for public access.
  url: https://www.parliament.uk/
  country: gb
  country_label: United Kingdom
  official: true